In [2]:
import numpy as np

# **A. REPRODUCIBLE NORMALIZATION**



In [34]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
x = X.mean()
σ = X.std()
X_normalized = (X - x)/σ
x_normalized = X_normalized.mean()
σ_normalized = X_normalized.std()

**X**




In [35]:
print(X)

[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


**X_normalized**

In [36]:
print(X_normalized)

[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


**x_normalized**

In [37]:
print(x_normalized)

0.0


**σ_normalized**

In [38]:
print(σ_normalized)

0.9999999999999999


In [39]:
np.save("X_normalized.npy",X_normalized)

# **B. CUBES DIVISIBLE BY 4 PROBLEM**

In [7]:
c = (np.arange(1, 101)**3).reshape(10, 10)
div4 = c%4 == 0
div_by_4 = c[div4].reshape(5,10)

**Shape of C**

In [8]:
print(c.shape)

(10, 10)


**div_by_4 array**

In [9]:
print(div_by_4)

[[      8      64     216     512    1000    1728    2744    4096    5832
     8000]
 [  10648   13824   17576   21952   27000   32768   39304   46656   54872
    64000]
 [  74088   85184   97336  110592  125000  140608  157464  175616  195112
   216000]
 [ 238328  262144  287496  314432  343000  373248  405224  438976  474552
   512000]
 [ 551368  592704  636056  681472  729000  778688  830584  884736  941192
  1000000]]


**Number of Elements**

In [10]:
display(div_by_4.size)

50

In [22]:
np.save("div_by_4.npy",div_by_4)

# **C. ABOVE-MEAN SQUARES PROBLEM**

In [17]:
S = (np.arange(1, 37)**2).reshape(6,6)
S_mean = np.mean(S)
above_mean = S[S > S_mean].reshape(3,5)

array([[ 484,  529,  576,  625,  676],
       [ 729,  784,  841,  900,  961],
       [1024, 1089, 1156, 1225, 1296]])

**Array of S**

In [18]:
display(S)

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

**Mean of S**

In [19]:
display(S_mean)

np.float64(450.1666666666667)

**above_mean array**

In [20]:
display(above_mean)

array([[ 484,  529,  576,  625,  676],
       [ 729,  784,  841,  900,  961],
       [1024, 1089, 1156, 1225, 1296]])

In [21]:
np.save("above_mean.npy",above_mean)